# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gitlab.dcb.kg/dcb/frontend/dcb-green
  pullPolicy: Always
  pullSecrets: dcb-registry-key

# Values: ClusterIP, NodePort, LoadBalancer
serviceType: ClusterIP

## Ports published to Service and redirected to Pods
servicePorts:
  - servicePort: 80
    containerPort: 3000
    protocol: TCP
    name: http

env:
  ENV: 'production'
  PORT: 3000
  URL: '/dcb-green'
  JWT: 'http://qa360-kube-master1.linux.doscredobank.kg/authentication/auth/token'
  BASE_URL: 'http://qa360-kube-master1.linux.doscredobank.kg'
  CLIENT_ID: '3717ee772ab8444db2787e733cab5bf0'

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/app-root: /
  rules:
    - http:
        paths:
          - backend:
              service:
                name: app-dcb-green
                port:
                  number: 80
            path: /dcb-green/(.*)
            pathType: Prefix
          - backend:
              service:
                name: app-dcb-green
                port:
                  number: 80
            path: /dcb-green
            pathType: Prefix
